/*
 * TeacherInfo.java
 *
 * Created on __DATE__, __TIME__
 */

package view.Teacher;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import dao.*;
import dbutil.*;
import model.*;

/**
 *
 * @author  __USER__
 */
public class TeacherInfo extends javax.swing.JFrame {
	
	public void setDefaultCloseOperation(int operation){
		operation=HIDE_ON_CLOSE;
	}


	private static String me;
	private static String tel;

	/** Creates new form TeacherInfo */
	public TeacherInfo(String me) {
		
		//改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}
		this.me = me;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		TsexText = new javax.swing.JTextField();
		TdeptText = new javax.swing.JTextField();
		TdegreeText = new javax.swing.JTextField();
		TitleText = new javax.swing.JTextField();
		TtelText = new javax.swing.JTextField();
		TnoText = new javax.swing.JTextField();
		TnameText = new javax.swing.JTextField();
		UP1 = new javax.swing.JButton();
		Reset = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6559\u5e08\u4fe1\u606f\u7ba1\u7406");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/学生证.png"))); // NOI18N

		jLabel2.setText("\u6559\u5e08\u53f7 \uff1a");

		jLabel3.setText("\u59d3   \u540d \uff1a");

		jLabel4.setText("\u6027  \u522b \uff1a");

		jLabel5.setText("\u9662  \u7cfb \uff1a");

		jLabel6.setText("\u5b66  \u5386 \uff1a");

		jLabel7.setText("\u804c  \u79f0 \uff1a");

		jLabel8.setText("\u7535  \u8bdd \uff1a");

		TtelText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TtelTextActionPerformed(evt);
			}
		});

		UP1.setText("\u4fee  \u6539");
		UP1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				UP1ActionPerformed(evt);
			}
		});

		Reset.setText("\u91cd  \u7f6e");
		Reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup().addGap(81, 81, 81)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jLabel3).addGap(18, 18, 18)
																		.addComponent(TnameText))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jLabel2).addGap(18, 18, 18)
																		.addComponent(TnoText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGap(45, 45, 45))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jLabel1).addGap(62, 62, 62)))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4).addComponent(jLabel5)
														.addComponent(jLabel6).addComponent(jLabel7)
														.addComponent(jLabel8))
												.addGap(26, 26, 26)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(TtelText).addComponent(TitleText)
														.addComponent(TdegreeText).addComponent(TdeptText)
														.addComponent(TsexText, javax.swing.GroupLayout.DEFAULT_SIZE,
																84, Short.MAX_VALUE)))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup().addGap(91, 91, 91)
												.addComponent(UP1, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(88, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addGap(45, 45, 45).addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4).addComponent(TsexText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5).addComponent(TdeptText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6).addComponent(TdegreeText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup().addGap(46, 46, 46).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 101,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jLabel7)
								.addComponent(TnoText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel8)
								.addComponent(TnameText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(TtelText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Reset).addComponent(UP1))
						.addGap(39, 39, 39)));
		setMessage();
		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void TtelTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//重置：
	private void ResetActionPerformed(java.awt.event.ActionEvent evt) {
		TtelText.setText("");
	}

	private void UP1ActionPerformed(java.awt.event.ActionEvent evt) {
		//获取电话号：
		tel = TtelText.getText();
		if (tel.length() < 0) {
			JOptionPane.showConfirmDialog(null, "电话号码位数错误！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (!StringUtil.isNumeric(tel)) {
			JOptionPane.showConfirmDialog(null, "电话号码应为数字！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		Teacher_Dao s = new Teacher_Dao();
		ResultSet rSet = s.teaSelecte(new Teacher(me, tel));
			rSet = s.teaSelecte(new Teacher(me));
			try{
			if (rSet.next()) {
				if (s.teaModify(me, new Teacher(rSet.getString(1), rSet.getString(2), rSet.getString(3),
						rSet.getString(4), rSet.getString(5), rSet.getString(6), tel, rSet.getString(8))) == 1) {
					setMessage();//修改完需要再设置一次
					JOptionPane.showConfirmDialog(null, "修改成功！", "提示", JOptionPane.CLOSED_OPTION);
				} else {
					JOptionPane.showConfirmDialog(null, "修改失败，电话号已被使用！", "提示", JOptionPane.CLOSED_OPTION);

				}
			}
			} catch (SQLException e1) {
			e1.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}


	private void setMessage() {
		Teacher_Dao s = new Teacher_Dao();
		ResultSet rSet = s.teaSelecte(new Teacher(me));

		try {
			if (rSet.next()) {
				TnoText.setText(rSet.getString(1));
				TnameText.setText(rSet.getString(2));
				TsexText.setText(rSet.getString(3));
				TdeptText.setText(rSet.getString(4));
				TdegreeText.setText(rSet.getString(5));
				TitleText.setText(rSet.getString(6));
				TtelText.setText(rSet.getString(7));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TeacherInfo(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Reset;
	private javax.swing.JTextField TdegreeText;
	private javax.swing.JTextField TdeptText;
	private javax.swing.JTextField TitleText;
	private javax.swing.JTextField TnameText;
	private javax.swing.JTextField TnoText;
	private javax.swing.JTextField TsexText;
	private javax.swing.JTextField TtelText;
	private javax.swing.JButton UP1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	// End of variables declaration//GEN-END:variables

}