/*
 * TeacherCourse.java
 *
 * Created on __DATE__, __TIME__
 */

package view.Teacher;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import dao.*;
import model.*;
import dbutil.*;
import view.manager.*;

/**
 *
 * @author  __USER__
 */
public class TeacherCourse extends javax.swing.JFrame {
	private static int sum;

	/** Creates new form TeacherCourse */
	private static String me;
	
	public void setDefaultCloseOperation(int operation){
		operation=HIDE_ON_CLOSE;
	}


	public TeacherCourse(String me) {

		//改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		this.me = me;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		Table = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();

		jLabel1.setText("jLabel1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6559\u5e08\u8bfe\u7a0b\u7ba1\u7406\u754c\u9762");

		Table.setModel(
				new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null } }, new String[] { "课程类型", "教师号", "课程号" }));
		Table.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				TableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(Table);

		jLabel2.setText("\u6559\u5e08\u6388\u8bfe\u8868\u663e\u793a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(176, 176, 176).addComponent(jLabel2)
						.addContainerGap(223, Short.MAX_VALUE))
				.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(27, 27, 27)
						.addComponent(jLabel2).addGap(27, 27, 27).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(42, Short.MAX_VALUE)));
		fillTableALL();
		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void TableMousePressed(java.awt.event.MouseEvent evt) {
		fillTableALL();
	}

	//将查询的内容显示到表上：

	private void fillTableALL() {
		sum = 0;
		DefaultTableModel dModel = (DefaultTableModel) Table.getModel();
		
		dModel.setRowCount(0);
		TC_Dao tc = new TC_Dao();
		ResultSet rs = tc.T_TCQuery(me);

		try {
			while (rs.next()) {
				Vector vector = new Vector();
				vector.add(rs.getInt(1));
				vector.add(rs.getString(2));
				vector.add(rs.getString(3));
				dModel.addRow(vector);
				sum++;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TeacherCourse(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable Table;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}