/*
 * TeacherLonFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package view.Teacher;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import view.mainlogin.MainLogin;
import view.manager.AboutUs;
import view.manager.StudentPassword;
import view.manager.TeacherPassword;

/**
 *
 * @author  __USER__
 */
public class TeacherLonFrm extends javax.swing.JFrame {

	private static String me;

	/** Creates new form TeacherLonFrm */
	public TeacherLonFrm(String me) {
		this.me = me;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		Setc = new javax.swing.JButton();
		Seme = new javax.swing.JButton();
		Upgrade = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		SSMS = new javax.swing.JMenu();
		password = new javax.swing.JMenuItem();
		Exit = new javax.swing.JMenuItem();
		AboutUs = new javax.swing.JMenu();
		hlep = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6559\u5e08\u767b\u5f55\u4e3b\u754c\u9762");
		setResizable(false);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/教师界面.jpg"))); // NOI18N

		Setc.setText("\u6388\u8bfe\u67e5\u8be2");
		Setc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SetcActionPerformed(evt);
			}
		});

		Seme.setText("\u4fe1\u606f\u7ba1\u7406");
		Seme.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SemeActionPerformed(evt);
			}
		});

		Upgrade.setText("\u6210\u7ee9\u5f55\u5165");
		Upgrade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				UpgradeActionPerformed(evt);
			}
		});

		SSMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/学生成绩管理系统主UI.png"))); // NOI18N
		SSMS.setText("\u7cfb\u7edf\u7ba1\u7406");
		SSMS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SSMSActionPerformed(evt);
			}

			private void SSMSActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/密码修改方.png"))); // NOI18N
		password.setText("\u5bc6\u7801\u4fee\u6539");
		password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwordActionPerformed(evt);
			}
		});
		SSMS.add(password);

		Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/退出系统红.png"))); // NOI18N
		Exit.setText("\u9000\u51fa\u7cfb\u7edf");
		Exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitActionPerformed(evt);
			}
		});
		SSMS.add(Exit);

		jMenuBar1.add(SSMS);

		AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/关于我们.png"))); // NOI18N
		AboutUs.setText("\u5173\u4e8e\u6211\u4eec");
		AboutUs.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AboutUsActionPerformed(evt);
			}

			private void AboutUsActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		hlep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/项目帮助.png"))); // NOI18N
		hlep.setText("\u9879\u76ee\u5e2e\u52a9");
		hlep.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hlepActionPerformed(evt);
			}
		});
		AboutUs.add(hlep);

		jMenuBar1.add(AboutUs);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(34, 34, 34)
						.addComponent(Setc, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(77, 77, 77)
						.addComponent(Seme, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
						.addComponent(Upgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(36, 36, 36)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Seme).addComponent(Setc).addComponent(Upgrade))
						.addContainerGap(32, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	void hlepActionPerformed(java.awt.event.ActionEvent evt) {
		new AboutUs().setVisible(true);
	}

//	private void HlepActionPerformed(java.awt.event.ActionEvent evt) {
//		//项目帮助
//		new AboutUs().setVisible(true);
//	}

	private void ExitActionPerformed(java.awt.event.ActionEvent evt) {
		//退出系统：
		int result = JOptionPane.showConfirmDialog(null, "是否退出系统");
		if (result == 0) {
			this.dispose();
			new MainLogin().setVisible(true);
		}
	}

	private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
		new TeacherPassword(me).setVisible(true);
	}

	//	private void SSMSActionPerformed(java.awt.event.ActionEvent evt) {
	//		// TODO add your handling code here:
	//	}

	//成绩：

	private void UpgradeActionPerformed(java.awt.event.ActionEvent evt) {
		new UPGra(me).setVisible(true);
	}

	//信息管理
	private void SemeActionPerformed(java.awt.event.ActionEvent evt) {
		new TeacherInfo(me).setVisible(true);
	}

	//授课管理
	private void SetcActionPerformed(java.awt.event.ActionEvent evt) {
		new TeacherCourse(me).setVisible(true);
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TeacherLonFrm(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu AboutUs;
	private javax.swing.JMenuItem Exit;
	private javax.swing.JMenu SSMS;
	private javax.swing.JButton Seme;
	private javax.swing.JButton Setc;
	private javax.swing.JButton Upgrade;
	private javax.swing.JMenuItem hlep;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem password;
	// End of variables declaration//GEN-END:variables

}