/*
 * AboutUs.java
 *
 * Created on __DATE__, __TIME__
 */

package view.manager;

import java.awt.Font;

import javax.swing.UIManager;

/**
 *
 * @author  __USER__
 */
public class AboutUs extends javax.swing.JFrame {
	public void setDefaultCloseOperation(int operation){
		operation=HIDE_ON_CLOSE;
	}

	/** Creates new form AboutUs */
	public AboutUs() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		ZZY = new javax.swing.JLabel();
		FHR = new javax.swing.JLabel();
		ZQZ = new javax.swing.JLabel();
		HZH = new javax.swing.JLabel();
		ItemTitle = new javax.swing.JLabel();
		Teacher = new javax.swing.JLabel();
		Time = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5173\u4e8e\u6211\u4eec");
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);

		ZZY.setFont(new java.awt.Font("楷体", 0, 18));
		ZZY.setText(
				"\u7ec4 \u957f:   \u90d1\u5353\u5a05     \u9879\u76ee\u6846\u67b6\u642d\u5efa\uff0c\u6559\u52a1\u5904\u5b50\u7cfb\u7edf\u7f16\u5199");

		FHR.setFont(new java.awt.Font("楷体", 0, 18));
		FHR.setText("\u7ec4 \u5458\uff1a  \u7b26\u6d69\u7136     \u5b66\u751f\u5b50\u7cfb\u7edf\u7f16\u5199");

		ZQZ.setFont(new java.awt.Font("楷体", 0, 18));
		ZQZ.setText("\u7ec4 \u5458\uff1a  \u6731\u542f\u91cd     \u6559\u5e08\u5b50\u7cfb\u7edf\u7f16\u5199");

		HZH.setFont(new java.awt.Font("楷体", 0, 18));
		HZH.setText(
				"\u7ec4 \u5458\uff1a  \u80e1\u632f\u534e     \u767b\u5f55/\u9000\u51fa\u5b50\u7cfb\u7edf\u7f16\u5199");

		ItemTitle.setFont(new java.awt.Font("仿宋", 1, 36));
		ItemTitle.setForeground(new java.awt.Color(204, 51, 255));
		ItemTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/关于我们主图标.png"))); // NOI18N
		ItemTitle.setText("\u5b66\u751f\u6210\u7ee9\u7ba1\u7406\u7cfb\u7edf");

		Teacher.setFont(new java.awt.Font("楷体", 0, 14));
		Teacher.setText("\u6307\u5bfc\u8001\u5e08\uff1a\u5f20\u5143");

		Time.setFont(new java.awt.Font("楷体", 0, 14));
		Time.setText("\u5f00\u53d1\u65f6\u95f4\uff1a2018/1/10\u81f3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(54, 54, 54)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(ItemTitle)
						.addComponent(HZH).addComponent(ZQZ).addComponent(FHR).addComponent(ZZY))
				.addContainerGap(40, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(315, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(Time).addComponent(Teacher))
								.addGap(82, 82, 82)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(31, 31, 31).addComponent(ItemTitle).addGap(18, 18, 18)
						.addComponent(ZZY).addGap(10, 10, 10).addComponent(FHR)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(ZQZ)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(HZH)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
						.addComponent(Teacher).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(Time).addGap(16, 16, 16)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AboutUs().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel FHR;
	private javax.swing.JLabel HZH;
	private javax.swing.JLabel ItemTitle;
	private javax.swing.JLabel Teacher;
	private javax.swing.JLabel Time;
	private javax.swing.JLabel ZQZ;
	private javax.swing.JLabel ZZY;
	// End of variables declaration//GEN-END:variables
}