/*
 * AdminiPassword.java
 *
 * Created on __DATE__, __TIME__
 */

package view.manager;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import dao.*;
import model.*;
import dbutil.*;

/**
 *
 * @author  __USER__
 */
public class AdminiPassword extends javax.swing.JFrame {

	private static String old;
	private static String input;
	private static String okinput;

	private static String me;
	public void setDefaultCloseOperation(int operation) {
		//API查看关闭默认方法是 直接关闭应用程序 此处实现隐藏
		https: //zhidao.baidu.com/question/447108412.html
		operation = HIDE_ON_CLOSE;
	}

	/** Creates new form AdminiPassword */
	public AdminiPassword(String me) {
		this.me=me;
		ViewBase.setFront();//设置字体
		initComponents();
		this.setSize(400, 300);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		OK = new javax.swing.JButton();
		Reset = new javax.swing.JButton();
		Input = new javax.swing.JLabel();
		OKInput = new javax.swing.JLabel();
		InputText = new javax.swing.JTextField();
		OKInputText = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		Old = new javax.swing.JLabel();
		OldText = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6211\u7684\u5bc6\u7801\u4fee\u6539");
		setMinimumSize(new java.awt.Dimension(400, 300));
		setResizable(false);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		OK.setText("\u786e  \u8ba4");
		OK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKActionPerformed(evt);
			}
		});
		getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, -1));

		Reset.setText("\u91cd  \u7f6e");
		Reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetActionPerformed(evt);
			}
		});
		getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

		Input.setText("\u8f93\u5165\u65b0\u5bc6\u7801 \uff1a");
		getContentPane().add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
		getContentPane().add(OKInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

//		InputText.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				InputTextActionPerformed(evt);
//			}
//		});
		getContentPane().add(InputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, -1));
		getContentPane().add(OKInputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, -1));

		jLabel1.setText("\u786e \u8ba4 \u5bc6 \u7801 \uff1a");
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 80, -1));

		Old.setText("\u8f93\u5165\u539f\u5bc6\u7801 \uff1a");
		getContentPane().add(Old, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
		getContentPane().add(OldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void OKActionPerformed(java.awt.event.ActionEvent evt) {
		messageGet();
		if (StringUtil.isEmpty(old)) {
			JOptionPane.showConfirmDialog(null, "原密码不能为空！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(input)) {
			JOptionPane.showConfirmDialog(null, "新密码不能为空！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(input)) {
			JOptionPane.showConfirmDialog(null, "新密码不能为空！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (!okinput.equals(input)) {
			JOptionPane.showConfirmDialog(null, "两次输入的密码不一致，请重新输入！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}

		AU_Dao aDao = new AU_Dao();
		ResultSet rSet = aDao.AUSelect(new Admini(me,old));//确认旧密码
		try {
			if (rSet.wasNull()) {
				return;
			}
			if (aDao.AUmodify(new Admini(me,input)) == 1) {//修改密码
				JOptionPane.showConfirmDialog(null, "修改成功！", "提示", JOptionPane.CLOSED_OPTION);
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}

	private void ResetActionPerformed(java.awt.event.ActionEvent evt) {
		this.InputText.setText("");
		this.OKInputText.setText("");
		this.OldText.setText("");
	}

	private void messageGet() {
		old = OldText.getText();
		input = InputText.getText();
		okinput = OKInputText.getText();
		//不能在此处定义类型 否则为局部变量
		
		//旧密码没有对应  确认的开发功能

	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminiPassword(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel Input;
	private javax.swing.JTextField InputText;
	private javax.swing.JButton OK;
	private javax.swing.JLabel OKInput;
	private javax.swing.JTextField OKInputText;
	private javax.swing.JLabel Old;
	private javax.swing.JTextField OldText;
	private javax.swing.JButton Reset;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}