/*
 * ResultAdmini.java
 *
 * Created on __DATE__, __TIME__
 */

package view.manager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import dao.*;
import dbutil.StringUtil;
import model.*;

/**
 *
 * @author  __USER__
 */
public class GradeAdmini extends javax.swing.JFrame {

	private static int count = 0;
	private static String sno;
	private static String cno;
	private static String cname;
	private static float grade;
	private static String credit;
	private static String tno;
	private static String tname;

	private static String me;
	private static int tc_id;

	public void setDefaultCloseOperation(int operation) {
		operation = HIDE_ON_CLOSE;
	}

	/** Creates new form ResultAdmini */
	public GradeAdmini(String me) {
		this.me = me;
		ViewBase.setFront();
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		GradeFind = new javax.swing.JTabbedPane();
		GradeTab = new javax.swing.JPanel();
		Sno = new javax.swing.JLabel();
		Find = new javax.swing.JButton();
		SnoText = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		Table = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		GradeText = new javax.swing.JTextField();
		GradeBook = new javax.swing.JLabel();
		SnoBook = new javax.swing.JLabel();
		SnoBookText = new javax.swing.JTextField();
		SnoTypeText = new javax.swing.JLabel();
		CnoTypeText = new javax.swing.JTextField();
		TC_id = new javax.swing.JLabel();
		TC_idText = new javax.swing.JTextField();
		ReInput = new javax.swing.JButton();
		Reset = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6210\u7ee9\u7ba1\u7406");
		setResizable(false);

		Sno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/用户3圆.png"))); // NOI18N
		Sno.setText("  \u5b66 \u751f \u53f7\uff1a");

		Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/查询.png"))); // NOI18N
		Find.setText("\u67e5  \u8be2");
		Find.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FindActionPerformed(evt);
			}
		});

		Table.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null } },
				new String[] { "学号", "课程类型", "成绩", "课程号", "课程名", "学分", "老师号", "教师名" }) {
			boolean[] canEdit = new boolean[] { true, false, false, true, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		Table.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				TableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(Table);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("\u8868\u5355\u64cd\u4f5c\uff1a"));

		GradeBook.setText("\u6210 \u7ee9\uff1a");

		SnoBook.setText("\u5b66 \u53f7\uff1a");

		SnoTypeText.setText("\u8bfe \u7a0b \u7c7b \u578b\uff1a");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(25, 25, 25).addComponent(SnoBook).addGap(18, 18, 18)
						.addComponent(SnoBookText, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(46, 46, 46).addComponent(SnoTypeText)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(CnoTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(42, 42, 42)
						.addComponent(GradeBook).addGap(18, 18, 18).addComponent(GradeText,
								javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(59, 59, 59)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(SnoBook)
								.addComponent(SnoBookText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(SnoTypeText)
								.addComponent(CnoTypeText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(GradeBook).addComponent(GradeText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(33, 33, 33)));

		TC_id.setText("\u8bfe\u7a0b\u7c7b\u578b \uff1a");

		ReInput.setText("\u4fee  \u6539");
		ReInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ReInputActionPerformed(evt);
			}
		});

		Reset.setText("\u91cd  \u7f6e");
		Reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout GradeTabLayout = new javax.swing.GroupLayout(GradeTab);
		GradeTab.setLayout(GradeTabLayout);
		GradeTabLayout.setHorizontalGroup(GradeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GradeTabLayout.createSequentialGroup()
						.addGap(98, 98, 98)
						.addComponent(ReInput, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
						.addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(155, 155, 155))
				.addGroup(GradeTabLayout.createSequentialGroup().addGap(54, 54, 54).addComponent(Sno)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(SnoText, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(41, 41, 41).addComponent(TC_id)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(TC_idText, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(65, 65, 65).addComponent(Find).addContainerGap(102, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						GradeTabLayout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE))
				.addGroup(GradeTabLayout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
						.addContainerGap()));
		GradeTabLayout
				.setVerticalGroup(GradeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(GradeTabLayout.createSequentialGroup().addGap(30, 30, 30).addGroup(GradeTabLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(Sno)
								.addComponent(SnoText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(TC_id)
								.addComponent(TC_idText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Find))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
										Short.MAX_VALUE)
								.addGroup(GradeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Reset).addComponent(ReInput))
								.addGap(36, 36, 36)));

		GradeFind.addTab("\u6210\u7ee9\u67e5\u8be2", GradeTab);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				GradeFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(GradeFind, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	// </editor-fold>
	//GEN-END:initComponents

	private void TableMousePressed(java.awt.event.MouseEvent evt) {
		//表单显示：
		int row = Table.getSelectedRow();
		count = 10;
		if (row < count) {
			SnoBookText.setText((String) Table.getValueAt(row, 0));
			CnoTypeText.setText(String.valueOf(Table.getValueAt(row, 1)));
			GradeText.setText(String.valueOf(Table.getValueAt(row, 2)));

		}

	}

	//重置
	private void ResetActionPerformed(java.awt.event.ActionEvent evt) {
		SnoText.setText("");
		GradeText.setText("");
		TC_idText.setText("");
		CnoTypeText.setText("");
		SnoBookText.setText("");
	}

	//修改 成绩
	private void ReInputActionPerformed(java.awt.event.ActionEvent evt) {
		String sno = SnoBookText.getText();
		String n = CnoTypeText.getText();
		if(!n.equals("")){
			tc_id = Integer.parseInt(n);
		}
		String g = GradeText.getText();
		if (g != null) {
			grade = Float.parseFloat(g);
		}
		//System.out.println(sno + "ooooooppppppppppppppp" + grade);
		SC_Dao sDao = new SC_Dao();
		//public Grade(int tC_id, String tno, String cno, String sno, float grade) {
		//String MODIFY = "update SC set Grade = " + sc.getGrade() + " where Sno = '" + sc.getSno()+"'";
		if (sDao.SCModiy(new Grade(tc_id, tno, cno, sno, grade)) == 1) {
			fillTable();
			JOptionPane.showConfirmDialog(null, "成绩修改成功！", "提示", JOptionPane.CLOSED_OPTION);
		} else {
			JOptionPane.showConfirmDialog(null, "修改失败，请检查填入的成绩!", "提示", JOptionPane.CLOSED_OPTION);
		}
	}

	private void FindActionPerformed(java.awt.event.ActionEvent evt) {
		//分组查找
		fillTable();
		//返回显示

	}

	private void fillTable() {
		DefaultTableModel dModel = (DefaultTableModel) Table.getModel();
		dModel.setRowCount(0);
		SC_Dao sc_DAO = new SC_Dao();
		String t = TC_idText.getText();//TC_idText
		if (!t.equals("")) {
			tc_id = Integer.parseInt(t);
		}
		sno = SnoText.getText();
		if(SnoText.getText().equals("")&&TC_idText.getText().equals("")){
			JOptionPane.showConfirmDialog(null, "检索信息不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return ;
		}
		ResultSet rs = sc_DAO.SCSelectGrade(sno, tc_id);
		count = 0;
		try {
			while (rs.next()) {
				Vector vector = new Vector();
				vector.add(rs.getString(1));
				vector.add(rs.getInt(2));
				vector.add(rs.getFloat(3));
				vector.add(rs.getString(4));
				vector.add(rs.getString(5));
				vector.add(rs.getInt(6));
				vector.add(rs.getString(7));
				vector.add(rs.getString(8));
				dModel.addRow(vector);
				count++;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
//		tc_id =0;
//		sno = "";
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GradeAdmini(me).setVisible(true);
			}
		});
		//https://jingyan.baidu.com/article/17bd8e52515abd85ab2bb8d3.html 表格知识
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField CnoTypeText;
	private javax.swing.JButton Find;
	private javax.swing.JLabel GradeBook;
	private javax.swing.JTabbedPane GradeFind;
	private javax.swing.JPanel GradeTab;
	private javax.swing.JTextField GradeText;
	private javax.swing.JButton ReInput;
	private javax.swing.JButton Reset;
	private javax.swing.JLabel Sno;
	private javax.swing.JLabel SnoBook;
	private javax.swing.JTextField SnoBookText;
	private javax.swing.JTextField SnoText;
	private javax.swing.JLabel SnoTypeText;
	private javax.swing.JLabel TC_id;
	private javax.swing.JTextField TC_idText;
	private javax.swing.JTable Table;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}