/*
 * StudentAdmin.java
 *
 * Created on __DATE__, __TIME__
 */

package view.manager;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import dao.*;
import dbutil.*;
/**
 *
 * @author  __USER__
 */
import model.Student;

public class StudentAdmini extends javax.swing.JFrame {
	public void setDefaultCloseOperation(int operation) {
		operation = HIDE_ON_CLOSE;
	}

	private static String sno;
	private static String sname;
	private static int sage;
	private static String ssex;
	private static String stel;
	private static String sdept;
	private static String sclass;
	//private static String password;//加显示 但是不能在此处修改
	private static int count = 0;

	/** Creates new form StudentAdmin */
	public StudentAdmini() {
		//改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		TabbedPane = new javax.swing.JTabbedPane();
		FindSInfo = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		InfoTableQ = new javax.swing.JTable();
		SnoQ = new javax.swing.JLabel();
		SnoTextQ = new javax.swing.JTextField();
		FindStudentQ = new javax.swing.JButton();
		RenewQ = new javax.swing.JButton();
		RenewPanel = new javax.swing.JPanel();
		RenewSnameQ = new javax.swing.JTextField();
		RenewSageQ = new javax.swing.JTextField();
		RenewSclassQ = new javax.swing.JTextField();
		RenewSdeptQ = new javax.swing.JTextField();
		RenewStelQ = new javax.swing.JTextField();
		RenewSnoQ = new javax.swing.JTextField();
		MQ = new javax.swing.JRadioButton();
		WQ = new javax.swing.JRadioButton();
		DeleteQ = new javax.swing.JButton();
		ResetQ = new javax.swing.JButton();
		AddSInfo = new javax.swing.JPanel();
		Add = new javax.swing.JButton();
		Replace = new javax.swing.JButton();
		SnoP = new javax.swing.JLabel();
		SnameP = new javax.swing.JLabel();
		SsexP = new javax.swing.JLabel();
		SageP = new javax.swing.JLabel();
		SdeptP = new javax.swing.JLabel();
		SclassP = new javax.swing.JLabel();
		StelP = new javax.swing.JLabel();
		SnoText = new javax.swing.JTextField();
		SnameText = new javax.swing.JTextField();
		SageText = new javax.swing.JTextField();
		SdeptText = new javax.swing.JTextField();
		SclassText = new javax.swing.JTextField();
		StelText = new javax.swing.JTextField();
		WButton = new javax.swing.JRadioButton();
		MButton = new javax.swing.JRadioButton();
		StudentInfoView = new javax.swing.JLabel();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406");
		setResizable(false);

		TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				TabbedPaneMousePressed(evt);
			}
		});

		FindSInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		InfoTableQ.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null } },
				new String[] { "Sno", "Sname", "Ssex", "Sage", "Sdept", "Sclass", "Stel" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		InfoTableQ.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				InfoTableQMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(InfoTableQ);

		FindSInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 780, 110));

		SnoQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/用户3圆.png"))); // NOI18N
		SnoQ.setText("  \u5b66\u751f\u5b66\u53f7\uff1a");
		FindSInfo.add(SnoQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, -1));

		SnoTextQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SnoTextQActionPerformed(evt);
			}

			private void SnoTextQActionPerformed(ActionEvent evt) {
				
			}
		});
		FindSInfo.add(SnoTextQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 130, -1));

		FindStudentQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/查询.png"))); // NOI18N
		FindStudentQ.setText("\u67e5    \u8be2");
		FindStudentQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FindStudentQActionPerformed(evt);
			}
		});
		FindSInfo.add(FindStudentQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, -1));

		RenewQ.setText("    \u4fee    \u6539    ");
		RenewQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RenewQActionPerformed(evt);
			}
		});
		FindSInfo.add(RenewQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, -1));

		RenewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("\u8868\u5355\u64cd\u4f5c"));
		RenewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		RenewPanel.add(RenewSnameQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));
		RenewPanel.add(RenewSageQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, -1));
		RenewPanel.add(RenewSclassQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 90, -1));
		RenewPanel.add(RenewSdeptQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 90, -1));
		RenewPanel.add(RenewStelQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 90, -1));
		RenewPanel.add(RenewSnoQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

		MQ.setText("\u7537");
		MQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MQActionPerformed(evt);
			}
		});
		RenewPanel.add(MQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

		WQ.setText("\u5973");
		WQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				WQActionPerformed(evt);
			}
		});
		RenewPanel.add(WQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

		FindSInfo.add(RenewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 770, 80));

		DeleteQ.setText("    \u5220    \u9664    ");
		DeleteQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DeleteQActionPerformed(evt);
			}
		});
		FindSInfo.add(DeleteQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 120, -1));

		ResetQ.setText("\u91cd    \u7f6e");
		ResetQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetQActionPerformed(evt);
			}
		});
		FindSInfo.add(ResetQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 120, -1));

		TabbedPane.addTab("\u5b66\u751f\u4fe1\u606f\u67e5\u8be2", FindSInfo);

		AddSInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		Add.setText("  \u6dfb    \u52a0  ");
		Add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddActionPerformed(evt);
			}
		});
		AddSInfo.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 120, -1));

		Replace.setText("   \u91cd    \u7f6e   ");
		Replace.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ReplaceActionPerformed(evt);
			}
		});
		AddSInfo.add(Replace, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 120, -1));

		SnoP.setText("\u5b66  \u53f7\uff1a");
		AddSInfo.add(SnoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

		SnameP.setText("\u59d3  \u540d\uff1a");
		AddSInfo.add(SnameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

		SsexP.setText("\u6027  \u522b\uff1a");
		AddSInfo.add(SsexP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

		SageP.setText("\u5e74  \u9f84\uff1a");
		AddSInfo.add(SageP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

		SdeptP.setText("\u4e13  \u4e1a\uff1a");
		AddSInfo.add(SdeptP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

		SclassP.setText("\u73ed  \u7ea7\uff1a");
		AddSInfo.add(SclassP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

		StelP.setText("\u7535\u8bdd\u53f7\uff1a");
		AddSInfo.add(StelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
		AddSInfo.add(SnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));

		SnameText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SnameTextActionPerformed(evt);
			}

			private void SnameTextActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});
		AddSInfo.add(SnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, -1));
		AddSInfo.add(SageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, -1));
		AddSInfo.add(SdeptText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, -1));

		SclassText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SclassTextActionPerformed(evt);
			}

			private void SclassTextActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});
		AddSInfo.add(SclassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 100, -1));
		AddSInfo.add(StelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, -1));

		WButton.setText("\u5973");
		WButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				WButtonActionPerformed(evt);
			}
		});
		AddSInfo.add(WButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

		MButton.setText("\u7537");
		MButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MButtonActionPerformed(evt);
			}
		});
		AddSInfo.add(MButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

		StudentInfoView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/学生证.png"))); // NOI18N
		AddSInfo.add(StudentInfoView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, 120));

		TabbedPane.addTab("\u5b66\u751f\u4fe1\u606f\u6dfb\u52a0", AddSInfo);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE));

		FillAll();
		pack();
	}

	private void WQActionPerformed(java.awt.event.ActionEvent evt) {
		if (WQ.isSelected()) {
			WQ.setSelected(true);
			MQ.setSelected(false);
		}
	}

	private void MQActionPerformed(java.awt.event.ActionEvent evt) {
		if (MQ.isSelected()) {
			MQ.setSelected(true);
			WQ.setSelected(false);
		}
	}

	private void TabbedPaneMousePressed(java.awt.event.MouseEvent evt) {
		FillAll();
	}

	private void RenewQActionPerformed(java.awt.event.ActionEvent evt) {
		AddGetQ();
		sno = RenewSnoQ.getText();
		Student_Dao sDao = new Student_Dao();
		if (sDao.stuModify(sno, new Student(sno, sname, ssex, sage, sdept, sclass, stel, null)) == 1) {
			JOptionPane.showConfirmDialog(null, "修改成功！", "提示", JOptionPane.CLOSED_OPTION);
			ReplaceActionPerformed(evt);
			FillAll();
		} else {
			JOptionPane.showConfirmDialog(null, "修改失败！请检查相关输入信息", "提示", JOptionPane.CLOSED_OPTION);
			ReplaceActionPerformed(evt);
			FillAll();
		}

	}

	private void FindStudentQActionPerformed(java.awt.event.ActionEvent evt) {
		FillAll();
	}

	//查询版面---------------------删除按钮功能实现
	private void DeleteQActionPerformed(java.awt.event.ActionEvent evt) {
		AddGetQ();
		sno = RenewSnoQ.getText();

		if ((!StringUtil.isEmpty(sno))) {
			Student_Dao sDao = new Student_Dao();
			if (sDao.stuDelete(new Student(sno, sname, ssex, sage, sdept, sclass, stel, null)) != 0) {
				JOptionPane.showConfirmDialog(null, "删除成功！", "提示", JOptionPane.CLOSED_OPTION);
				ResetQActionPerformed(evt);
				FillAll();
			}
		} else {
			JOptionPane.showConfirmDialog(null, "删除失败，请检查条件！", "提示", JOptionPane.CLOSED_OPTION);
		}
		this.FillAll();
	}

	//查询版面
	private void InfoTableQMousePressed(java.awt.event.MouseEvent evt) {
		int row = InfoTableQ.getSelectedRow();
		if (row < count) {//初始化定义为0
			RenewSnoQ.setText((String) InfoTableQ.getValueAt(row, 0));
			RenewSnameQ.setText((String) InfoTableQ.getValueAt(row, 1));
			if (InfoTableQ.getValueAt(row, 2).equals("男")) {
				MButton.setSelected(true);
				WButton.setSelected(false);
			} else {
				WButton.setSelected(false);
				MButton.setSelected(true);
			}
			if ((int) InfoTableQ.getValueAt(row, 3) > 0) {
				RenewSageQ.setText(String.valueOf(InfoTableQ.getValueAt(row, 3)));
			} else {
				RenewSageQ.setText(null);
			}
			RenewSdeptQ.setText((String) InfoTableQ.getValueAt(row, 4));
			RenewSclassQ.setText((String) InfoTableQ.getValueAt(row, 5));
			RenewStelQ.setText((String) InfoTableQ.getValueAt(row, 6));
		}
	}
	
	private void ResetQActionPerformed(java.awt.event.ActionEvent evt) {
		this.SnoTextQ.setText("");
		this.RenewSnoQ.setText("");
		this.RenewSnameQ.setText("");
		MQ.setSelected(false);
		WQ.setSelected(false);
		RenewSageQ.setText("");
		RenewSdeptQ.setText("");
		RenewSclassQ.setText("");
		RenewStelQ.setText("");
	}
	private void AddGetQ() {
		sno = SnoTextQ.getText();
		sname = RenewSnameQ.getText();
		if (MQ.isSelected()) {
			ssex = "男";
		} else if (WQ.isSelected()) {
			ssex = "女";
		} else {
			ssex = null;
		}
		String age = RenewSageQ.getText();
		if (!age.equals("") && StringUtil.isNumeric(age) && !age.equals(0)) {
			sage = Integer.parseInt(age);
		} else {
			sage = 0;
		}
		sdept = RenewSdeptQ.getText();
		sclass = RenewSclassQ.getText();
		stel = RenewStelQ.getText();

	}
	
	

	
	
	//学生信息添加：
	private void WButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (WButton.isSelected()) {
			WButton.setSelected(true);
			MButton.setSelected(false);
		}
	}
	private void MButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (MButton.isSelected()) {
			MButton.setSelected(true);
			WButton.setSelected(false);
		}
	}
	private void AddActionPerformed(java.awt.event.ActionEvent evt) {
		addGetP();
		if (StringUtil.isEmpty(sno)) {
			JOptionPane.showConfirmDialog(null, "学号不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(sname)) {
			JOptionPane.showConfirmDialog(null, "姓名不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (ssex == "无") {
			JOptionPane.showConfirmDialog(null, "性别不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(sage)) {
			JOptionPane.showConfirmDialog(null, "年龄不能为空|0!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (sage > 255) {
			JOptionPane.showConfirmDialog(null, "年龄不符合实际！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(sdept)) {
			JOptionPane.showConfirmDialog(null, "专业不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(sclass)) {
			JOptionPane.showConfirmDialog(null, "班级不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (StringUtil.isEmpty(stel)) {
			JOptionPane.showConfirmDialog(null, "电话号码不能为空!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (!StringUtil.isNumeric(stel)) {
			JOptionPane.showConfirmDialog(null, "电话号码不能为非数字!", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		if (stel.length() > 11) {
			JOptionPane.showConfirmDialog(null, "电话号码位数错误！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		Student_Dao sDao = new Student_Dao();//sno,sname, ssex,sage,sdept, sclass, stel, null
		if (sDao.stuInsert(new Student(sno, sname, ssex, sage, sdept, sclass, stel, null)) == 1) {//返回值是0
			JOptionPane.showConfirmDialog(null, "添加成功!", "提示", JOptionPane.CLOSED_OPTION);
			ReplaceActionPerformed(evt);
		} else {
			JOptionPane.showConfirmDialog(null, "学号或电话已被使用!请重新输入", "提示", JOptionPane.CLOSED_OPTION);
		}
		BaseDao.close();
	}
	private void ReplaceActionPerformed(java.awt.event.ActionEvent evt) {
		this.SnoText.setText("");
		this.SnameText.setText("");
		this.SclassText.setText("");
		this.SdeptText.setText("");
		this.SageText.setText("");
		this.StelText.setText("");
		this.WButton.setSelected(false);
		this.MButton.setSelected(false);

	}
	private void addGetP() {
		sno = SnoText.getText();
		sname = SnameText.getText();
		String age = SageText.getText();
		if (!age.equals("") && StringUtil.isNumeric(age)) {
			sage = Integer.parseInt(age);
		} else {
			sage = 0;
		}
		sdept = SdeptText.getText();
		sclass = SclassText.getText();
		stel = StelText.getText();
		if (MButton.isSelected()) {
			ssex = "男";
		} else if (WButton.isSelected()) {
			ssex = "女";
		} else {
			ssex = "无";
		}

	}

	

	public void FillAll() {
		AddGetQ();
		DefaultTableModel dModel = (DefaultTableModel) InfoTableQ.getModel();
		System.out.println(sno);
		dModel.setRowCount(0);
		count = 0;

		Student_Dao sDao = new Student_Dao();

		ResultSet rSet = sDao.stuSelecte(new Student(sno, sname, ssex, sage, sdept, sclass, stel, null));
		try {
			while (rSet.next()) {
				Vector vector = new Vector();
				vector.add(rSet.getString(1));//sno
				vector.add(rSet.getString(2));//sname
				vector.add(rSet.getString(3));//ssex
				if (rSet.getInt(4) > 0) {//sage
					vector.add(rSet.getInt(4));
				} else {
					vector.add(0);
				}
				vector.add(rSet.getString(5));//sdept
				vector.add(rSet.getString(6));//sclass
				vector.add(rSet.getString(7));//stel
				dModel.addRow(vector);
				count++;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}

	

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentAdmini().setVisible(true);

			}
		});
	}

	private javax.swing.JButton Add;
	private javax.swing.JPanel AddSInfo;
	private javax.swing.JButton DeleteQ;
	private javax.swing.JPanel FindSInfo;
	private javax.swing.JButton FindStudentQ;
	private javax.swing.JTable InfoTableQ;
	private javax.swing.JRadioButton MButton;
	private javax.swing.JRadioButton MQ;
	private javax.swing.JPanel RenewPanel;
	private javax.swing.JButton RenewQ;
	private javax.swing.JTextField RenewSageQ;
	private javax.swing.JTextField RenewSclassQ;
	private javax.swing.JTextField RenewSdeptQ;
	private javax.swing.JTextField RenewSnameQ;
	private javax.swing.JTextField RenewSnoQ;
	private javax.swing.JTextField RenewStelQ;
	private javax.swing.JButton Replace;
	private javax.swing.JButton ResetQ;
	private javax.swing.JLabel SageP;
	private javax.swing.JTextField SageText;
	private javax.swing.JLabel SclassP;
	private javax.swing.JTextField SclassText;
	private javax.swing.JLabel SdeptP;
	private javax.swing.JTextField SdeptText;
	private javax.swing.JLabel SnameP;
	private javax.swing.JTextField SnameText;
	private javax.swing.JLabel SnoP;
	private javax.swing.JLabel SnoQ;
	private javax.swing.JTextField SnoText;
	private javax.swing.JTextField SnoTextQ;
	private javax.swing.JLabel SsexP;
	private javax.swing.JLabel StelP;
	private javax.swing.JTextField StelText;
	private javax.swing.JLabel StudentInfoView;
	private javax.swing.JTabbedPane TabbedPane;
	private javax.swing.JRadioButton WButton;
	private javax.swing.JRadioButton WQ;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	

}