/*
 * StudentPassword.java
 *
 * Created on __DATE__, __TIME__
 */

package view.manager;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import dao.*;
import model.*;
import dbutil.*;
import view.manager.ViewBase;

/**
 *
 * @author  __USER__
 */
public class StudentPassword extends javax.swing.JFrame {
	
	private static String sno;
	private static String input;
	private static String okinput;
	private static String me;
	
	public void setDefaultCloseOperation(int operation) {
		operation = HIDE_ON_CLOSE;
	}
	

	/** Creates new form StudentPassword */
	public StudentPassword(String me) {
		this.me = me;
        ViewBase.setFront();//设置字体
		initComponents();
		this.setSize(400, 300);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		OK = new javax.swing.JButton();
		Reset = new javax.swing.JButton();
		Sno = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		OKInput = new javax.swing.JLabel();
		SnoText = new javax.swing.JTextField();
		OKInputText = new javax.swing.JTextField();
		InputText = new javax.swing.JTextField();
		Input = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u5bc6\u7801\u4fee\u6539");
		setResizable(false);
		setSize(new java.awt.Dimension(0, 0));
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		OK.setText("\u786e     \u5b9a");
		OK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKActionPerformed(evt);
			}
		});
		getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, -1));

		Reset.setText("\u91cd     \u7f6e");
		Reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetActionPerformed(evt);
			}
		});
		getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, -1));

		Sno.setText("\u8f93 \u5165 \u5b66 \u53f7\uff1a");
		getContentPane().add(Sno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
		getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

		OKInput.setText("\u786e \u8ba4 \u5bc6 \u7801\uff1a");
		getContentPane().add(OKInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
		getContentPane().add(SnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));
		getContentPane().add(OKInputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, -1));
		getContentPane().add(InputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

		Input.setText("\u8f93 \u5165 \u5bc6 \u7801\uff1a");
		getContentPane().add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, -1));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	//确定按钮：
	private void OKActionPerformed(java.awt.event.ActionEvent evt) {
		
		messageGet();
		if(StringUtil.isEmpty(sno)){
			JOptionPane.showConfirmDialog(null, "学号不能为空！","提示",JOptionPane.CLOSED_OPTION);
			return;
		}
		if(StringUtil.isEmpty(input)){
			JOptionPane.showConfirmDialog(null, "新密码不能为空！","提示",JOptionPane.CLOSED_OPTION);
			return;
		}
		if(StringUtil.isEmpty(okinput)){
			JOptionPane.showConfirmDialog(null, "请输入确认密码！","提示",JOptionPane.CLOSED_OPTION);
			return;
		}
		if (!okinput.equals(input)) {
			JOptionPane.showConfirmDialog(null, "两次输入的密码不一致，请重新输入！","提示",JOptionPane.CLOSED_OPTION);
			return;
		}
		
		Student_Dao stu = new Student_Dao();
		ResultSet rSet = stu.stuSelecte(new Student(sno));
		try {
			if(rSet.next()){
				if(stu.stuModify(sno, new Student(rSet.getString(1),rSet.getString(2),rSet.getString(3),
						rSet.getInt(4),rSet.getString(5),rSet.getString(6),rSet.getString(7), okinput)) == 1){
					JOptionPane.showConfirmDialog(null, "修改成功！","提示",JOptionPane.CLOSED_OPTION);
				}
			}else {
				JOptionPane.showConfirmDialog(null, "修改失败，请检查学号是否正确！","警告",JOptionPane.CLOSED_OPTION);
			}
		} catch (SQLException e1) {
			e1.printStackTrace();
		}finally{
			BaseDao.close();
		}
	}

		
	//重置：
	private void ResetActionPerformed(java.awt.event.ActionEvent evt) {
		this.SnoText.setText("");
		this.InputText.setText("");
		this.OKInputText.setText("");
	}
	private void messageGet(){
		 sno = SnoText.getText();
	     input = InputText.getText();
		 okinput = OKInputText.getText();
		 //不能在此处定义类型 否则为局部变量
		
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentPassword(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel Input;
	private javax.swing.JTextField InputText;
	private javax.swing.JButton OK;
	private javax.swing.JLabel OKInput;
	private javax.swing.JTextField OKInputText;
	private javax.swing.JLabel 	Sno;
	private javax.swing.JButton Reset;
	private javax.swing.JTextField SnoText;
	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}