/*
 * StudentInfoModify.java
 *
 * Created on __DATE__, __TIME__
 */

package view.student;

import view.manager.ViewBase;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import dao.*;
import dbutil.*;
import model.Student;
import dbutil.*;

/**
 *
 * @author  __USER__
 */
public class StudentInfoModify extends javax.swing.JFrame {

	private static String sno;
	private static String sname;
	private static int sage;
	private static String ssex;
	private static String stel;
	private static String sdept;
	private static String sclass;

	private static String me;
	
	

	public void setDefaultCloseOperation(int operation) {
		operation = HIDE_ON_CLOSE;
	}

	/** Creates new form StudentInfoModify */
	public StudentInfoModify(String me) {
		this.me=me;//将登录人学号记录
		ViewBase.setFront();
		initComponents();
		setMessage();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		SnoT = new javax.swing.JLabel();
		SnameT = new javax.swing.JLabel();
		SsexT = new javax.swing.JLabel();
		SageT = new javax.swing.JLabel();
		SdeptT = new javax.swing.JLabel();
		SclassT = new javax.swing.JLabel();
		TtelT = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		SnoText = new javax.swing.JTextField();
		SnameText = new javax.swing.JTextField();
		SsexText = new javax.swing.JTextField();
		SageText = new javax.swing.JTextField();
		SdeptText = new javax.swing.JTextField();
		SclassText = new javax.swing.JTextField();
		StelText = new javax.swing.JTextField();
		ModifyT = new javax.swing.JButton();
		RsetT = new javax.swing.JButton();

		jButton1.setText("jButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u4fe1\u606f\u4fee\u6539");
		setMinimumSize(new java.awt.Dimension(470, 350));
		setResizable(false);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		SnoT.setText("\u5b66 \u53f7 \uff1a");
		getContentPane().add(SnoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

		SnameT.setText("\u59d3 \u540d \uff1a");
		getContentPane().add(SnameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

		SsexT.setText("\u6027 \u522b \uff1a");
		getContentPane().add(SsexT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

		SageT.setText("\u5e74 \u9f84 \uff1a");
		getContentPane().add(SageT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

		SdeptT.setText("\u4e13 \u4e1a \uff1a");
		getContentPane().add(SdeptT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

		SclassT.setText("\u73ed \u7ea7 \uff1a");
		getContentPane().add(SclassT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

		TtelT.setText("\u7535 \u8bdd \uff1a");
		getContentPane().add(TtelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
		getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
		getContentPane().add(SnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, -1));

		SnameText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			
			}
		});
		getContentPane().add(SnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

		SsexText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			
			}
		});
		getContentPane().add(SsexText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, -1));
		getContentPane().add(SageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, -1));
		getContentPane().add(SdeptText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));
		getContentPane().add(SclassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 90, -1));
		getContentPane().add(StelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 90, -1));

		ModifyT.setText("\u4fee  \u6539");
		ModifyT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ModifyTActionPerformed(evt);
			}
		});
		getContentPane().add(ModifyT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, -1));

		RsetT.setText("\u91cd  \u7f6e");
		RsetT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RsetTActionPerformed(evt);
			}
		});
		getContentPane().add(RsetT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, -1));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
		//修改：
   
	
	
	
	//修改电话号码
	private void ModifyTActionPerformed(java.awt.event.ActionEvent evt) {
		stel = StelText.getText();
	
		System.out.println(stel+"ssssssssssssss"+me);
		if (stel.length() <11) {
			JOptionPane.showConfirmDialog(null, "电话号码位数错误！", "提示", JOptionPane.CLOSED_OPTION);
			return;
		}
		Student_Dao st=new Student_Dao();
		
		if (st.telModiy(stel, me)==1) {
		JOptionPane.showConfirmDialog(null, "修改成功！", "提示", JOptionPane.CLOSED_OPTION);
		setMessage();
	   } else {
				JOptionPane.showConfirmDialog(null, "修改失败！", "提示", JOptionPane.CLOSED_OPTION);

		}
		BaseDao.close();
	

	}


	//重置：
	void RsetTActionPerformed(java.awt.event.ActionEvent evt) {
		StelText.setText("");//只有电话可以置空
	}

	//学生信息显示
	private void setMessage() {
		Student_Dao stuDao = new Student_Dao();
		ResultSet rSet = stuDao.stuSelecte(new Student(sno));

		try {
			if (rSet.next()) {
				SnoText.setText(rSet.getString(1));
				SnameText.setText(rSet.getString(2));
				SsexText.setText(rSet.getString(3));
				SageText.setText(Integer.toString(rSet.getInt(4)));
				SdeptText.setText(rSet.getString(5));
				SclassText.setText(rSet.getString(6));
				StelText.setText(rSet.getString(7));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentInfoModify(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton ModifyT;
	private javax.swing.JButton RsetT;
	private javax.swing.JLabel SageT;
	private javax.swing.JTextField SageText;
	private javax.swing.JLabel SclassT;
	private javax.swing.JTextField SclassText;
	private javax.swing.JLabel SdeptT;
	private javax.swing.JTextField SdeptText;
	private javax.swing.JLabel SnameT;
	private javax.swing.JTextField SnameText;
	private javax.swing.JLabel SnoT;
	private javax.swing.JTextField SnoText;
	private javax.swing.JLabel SsexT;
	private javax.swing.JTextField SsexText;
	private javax.swing.JTextField StelText;
	private javax.swing.JLabel TtelT;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel8;
	// End of variables declaration//GEN-END:variables

}