/*
         * StudentAdmini.java
 *
 * Created on __DATE__, __TIME__
 */

package view.student;

import javax.swing.JOptionPane;

import view.mainlogin.MainLogin;
import view.manager.AboutUs;
import view.manager.StudentAdmini;
import view.manager.StudentPassword;

/**
 *
 * @author  __USER__
 */
public class StudentALonFrm extends javax.swing.JFrame {
	private static String me;

	/** Creates new form StudentAdmini */
	public StudentALonFrm(String me) {
		this.me = me;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		SelectCourse = new javax.swing.JButton();
		FindGrade = new javax.swing.JButton();
		ResetInfo = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		SSMS = new javax.swing.JMenu();
		PassWordItem = new javax.swing.JMenuItem();
		Exit = new javax.swing.JMenuItem();
		Help = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u767b\u5f55\u4e3b\u754c\u9762");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/中北大学学生界面.jpg"))); // NOI18N

		SelectCourse.setText("\u5b66\u751f\u9009\u8bfe");
		SelectCourse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SelectCourseActionPerformed(evt);
			}
		});

		FindGrade.setText("\u5b66\u751f\u67e5\u5206");
		FindGrade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FindGradeActionPerformed(evt);
			}
		});

		ResetInfo.setText("\u4fee\u6539\u4fe1\u606f");
		ResetInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ResetInfoActionPerformed(evt);
			}
		});

		SSMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/学生成绩管理系统主UI.png"))); // NOI18N
		SSMS.setText("\u7cfb\u7edf\u7ba1\u7406");
		SSMS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SSMSActionPerformed(evt);
			}
		});

		PassWordItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/密码修改方.png"))); // NOI18N
		PassWordItem.setText("\u5bc6\u7801\u4fee\u6539");
		PassWordItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PassWordItemActionPerformed(evt);
			}
		});
		SSMS.add(PassWordItem);

		Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/退出系统红.png"))); // NOI18N
		Exit.setText("\u9000\u51fa\u7cfb\u7edf");
		Exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitActionPerformed(evt);
			}
		});
		SSMS.add(Exit);

		jMenuBar1.add(SSMS);

		Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/关于我们.png"))); // NOI18N
		Help.setText("\u5173\u4e8e\u6211\u4eec");
		Help.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HelpActionPerformed(evt);
			}
		});

		jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/项目帮助.png"))); // NOI18N
		jMenuItem3.setText("\u9879\u76ee\u5e2e\u52a9");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		Help.add(jMenuItem3);

		jMenuBar1.add(Help);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup().addGap(43, 43, 43)
						.addComponent(SelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(68, 68, 68)
						.addComponent(FindGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(72, 72, 72).addComponent(ResetInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(29, 29, 29)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(FindGrade).addComponent(ResetInfo).addComponent(SelectCourse))
						.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		new AboutUs().setVisible(true);
	}

	private void ExitActionPerformed(java.awt.event.ActionEvent evt) {
		//退出系统：
		int result = JOptionPane.showConfirmDialog(null, "是否退出系统");
		if (result == 0) {
			this.dispose();
			new MainLogin().setVisible(true);
		}
	}

	private void PassWordItemActionPerformed(java.awt.event.ActionEvent evt) {
		new StudentPassword(me).setVisible(true);
	}

	//学生信息修改：
	private void ResetInfoActionPerformed(java.awt.event.ActionEvent evt) {
		new StudentInfoModify(me).setVisible(true);
	}

	//学生查分：
	private void FindGradeActionPerformed(java.awt.event.ActionEvent evt) {
		new StudentFindCredit(me).setVisible(true);
		;
	}

	//学生选课：
	private void SelectCourseActionPerformed(java.awt.event.ActionEvent evt) {
		new StudentChooseCourse(me).setVisible(true);
	}

	private void SSMSActionPerformed(java.awt.event.ActionEvent evt) {
		//学生密码修改
	}

	private void HelpActionPerformed(java.awt.event.ActionEvent evt) {
		//关于我们
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentALonFrm(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem Exit;
	private javax.swing.JButton FindGrade;
	private javax.swing.JMenu Help;
	private javax.swing.JMenuItem PassWordItem;
	private javax.swing.JButton ResetInfo;
	private javax.swing.JMenu SSMS;
	private javax.swing.JButton SelectCourse;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem3;
	// End of variables declaration//GEN-END:variables

}