/*
 * StudentChooseCourse.java
 *
 * Created on __DATE__, __TIME__
 */

package view.student;

import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import dao.*;
import dbutil.*;
import model.*;



/**
 *
 * @author  __USER__
 */
public class StudentChooseCourse extends javax.swing.JFrame {

	private static String me;

	
	private static int count = 0;
	private static int sum = 0;

	private static int tc_id;
	private static String tno;
	private static String sno;
	private static String cno;
	
	
	public void setDefaultCloseOperation(int operation) {
		operation = HIDE_ON_CLOSE;
	}
	

	/** Creates new form StudentChooseCourse */
	public StudentChooseCourse(String me) {
		this.me = me;
		sno = me;
		initComponents();
		fillTableALL();
		fillTableSelect(ChooseCourseShow);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		Cno = new javax.swing.JLabel();
		CnoText = new javax.swing.JTextField();
		FindB = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		Course = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		OKB = new javax.swing.JButton();
		CnoTypeText = new javax.swing.JTextField();
		TnoType = new javax.swing.JTextField();
		CnoType = new javax.swing.JLabel();
		Tno = new javax.swing.JLabel();
		Delete = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		ChooseCourseShow = new javax.swing.JTable();
		jLabel = new javax.swing.JLabel();
		ReSetQ = new javax.swing.JButton();

		jTable2.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(jTable2);

		jTable3.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(jTable3);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u9009\u8bfe");

		Cno.setText("\u8bfe\u7a0b\u53f7\uff1a");

		FindB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/查询.png"))); // NOI18N
		FindB.setText("\u67e5  \u8be2");
		FindB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FindBActionPerformed(evt);
			}
		});

		Course.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null } },
				new String[] { "课程类型", "课程号", "课程名", "学分", "教师号", "教师名" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		Course.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				CourseMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(Course);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("\u9009\u8bfe\u8868\u5355\u64cd\u4f5c\uff1a"));

		OKB.setText("\u9009  \u5b9a");
		OKB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKBActionPerformed(evt);
			}
		});

		CnoType.setText("\u8bfe\u7a0b\u7c7b\u578b \uff1a");

		Tno.setText("\u6559 \u5e08 \u53f7\uff1a");

		Delete.setText("\u5220  \u9664");
		Delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DeleteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(28, 28, 28).addComponent(CnoType)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(CnoTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(Tno)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(TnoType, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(29, 29, 29)
						.addComponent(OKB, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(58, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(20, Short.MAX_VALUE).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(CnoType)
								.addComponent(CnoTypeText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Tno)
								.addComponent(TnoType, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(OKB).addComponent(Delete))));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("\u9009\u8bfe\u7ed3\u679c\uff1a"));

		ChooseCourseShow.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null } },
				new String[] { "课程类型", "课程号", "课程名", "学分", "教师号", "教师名" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		ChooseCourseShow.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				ChooseCourseShowMousePressed(evt);
			}

			
		});
		jScrollPane4.setViewportView(ChooseCourseShow);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jLabel.setText("\u8bfe\u7a0b\u5c55\u793a\uff1a");

		ReSetQ.setText("\u91cd  \u7f6e");
		ReSetQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ReSetQActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel).addGap(73, 73, 73)
						.addComponent(Cno).addGap(29, 29, 29)
						.addComponent(CnoText, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(65, 65, 65).addComponent(FindB).addGap(35, 35, 35)
						.addComponent(ReSetQ, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(62, Short.MAX_VALUE))
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap(47, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(Cno)
								.addComponent(CnoText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(FindB).addComponent(ReSetQ)).addGap(24, 24, 24))
						.addGroup(layout.createSequentialGroup().addComponent(jLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jPanel2,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)));

		fillTableALL();
		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	//选定按钮------选择课程：
	private void OKBActionPerformed(java.awt.event.ActionEvent evt) {
		if (!StringUtil.isEmpty(CnoTypeText.getText())&&!StringUtil.isEmpty(TnoType.getText())) {
			    String z = CnoTypeText.getText();
			    if(!z.equals("")){
			    	tc_id = Integer.parseInt(z);
			    }
			    SC_Dao sc = new SC_Dao();
			    if(sc.SCInsert(new Grade(sno,tc_id,0.0f)) == 1){
					fillTableSelect(ChooseCourseShow);
			    	JOptionPane.showConfirmDialog(null, "成功选修该课程！","提示",JOptionPane.CLOSED_OPTION);
			    }else{
			    	JOptionPane.showConfirmDialog(null, "选修失败确认输入内容！","提示",JOptionPane.CLOSED_OPTION);
			    }
			}else{
				JOptionPane.showConfirmDialog(null, "选课信息未输入完全！","提示",JOptionPane.CLOSED_OPTION);
			}
		
	}

	//重置：
	private void ReSetQActionPerformed(java.awt.event.ActionEvent evt) {
		CnoTypeText.setText("");
		CnoText.setText("");
		TnoType.setText("");
	}

	// </editor-fold>
	//GEN-END:initComponents

	//根据课程类型删除选课
	private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {
		if (!StringUtil.isEmpty(CnoTypeText.getText())) {
			SC_Dao sc = new SC_Dao();//String sno,int tC_id, float grade
			sno = me;
			String r = CnoTypeText.getText();
			//System.out.println(sno+"   "+tc_id);
			if(!r.equals("")){
				tc_id = Integer.parseInt(r);
			} 
		
			if(sc.SCdelete(new Grade(sno,tc_id,0.0f))==1){
				fillTableSelect(ChooseCourseShow);
				JOptionPane.showConfirmDialog(null, "删除成功！","提示",JOptionPane.CLOSED_OPTION);	
			}else{
				JOptionPane.showConfirmDialog(null, "删除失败，请核对输入！","提示",JOptionPane.CLOSED_OPTION);
			}
		}
	//====	tc_id = 0; 

	}

	private void ChooseCourseShowMousePressed(java.awt.event.MouseEvent evt) {
		int row = ChooseCourseShow.getSelectedRow();
		count = 30; 
		if (row <= count) {
			CnoTypeText.setText((String) Course.getValueAt(row, 0));
			TnoType.setText((String) Course.getValueAt(row, 4));
		}
	}
	
	

	private void CourseMousePressed(java.awt.event.MouseEvent evt) {
		int row = Course.getSelectedRow();
		sum = 20;
		if (row < sum) {
			CnoTypeText.setText((String) Course.getValueAt(row, 0));
			TnoType.setText((String) Course.getValueAt(row, 4));
		}
	}

	//可选课程内容查询结果显示--button：++++++++++++++++++++++++++++
	private void FindBActionPerformed(java.awt.event.ActionEvent evt) {
		String cno =CnoText.getText();
		if(StringUtil.isEmpty(cno)) {
			fillTableALL();
			
		}
		else {
		
			fillTableQuery( cno);
		}
			
	}
		

	
	//do 显示所有可选课课程
	private void fillTableALL() {
		//cno =CnoText.getText(); 
		sum = 0;
		DefaultTableModel dModel = (DefaultTableModel) Course.getModel();
		dModel.setRowCount(0);
		TC_Dao tc = new TC_Dao();
		ResultSet rs = tc.TCQuery();

		try {
			while (rs.next()) {
				Vector vector = new Vector();
				vector.add(rs.getString(1));
				vector.add(rs.getString(2));
				vector.add(rs.getString(3));
				vector.add(rs.getString(4));
				vector.add(rs.getString(5));
				vector.add(rs.getString(6));
				dModel.addRow(vector);
				sum++;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}
	
	//显示根据课程号查询的可选课程列表
	private void fillTableQuery(String cno) {
		//cno =CnoText.getText(); 
		sum = 0;
		DefaultTableModel dModel = (DefaultTableModel) Course.getModel();
		dModel.setRowCount(0);
		TC_Dao tc = new TC_Dao();
		ResultSet rs = tc.TCQuery_Cno(cno);

		try {
			while (rs.next()) {
				Vector vector = new Vector();
				vector.add(rs.getString(1));
				vector.add(rs.getString(2));
				vector.add(rs.getString(3));
				vector.add(rs.getString(4));
				vector.add(rs.getString(5));
				vector.add(rs.getString(6));
				dModel.addRow(vector);
				sum++;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}


	//学生已选课程显示
	private void fillTableSelect(JTable jt) {
		tno = TnoType.getText();
		count = 0;
		DefaultTableModel dModel = (DefaultTableModel) jt.getModel();
		dModel.setRowCount(0);
		SC_Dao sc = new SC_Dao();
		ResultSet rs = sc.SCSelectS(me);//String TC_id, int Cno
		try {
			while (rs.next()) {
				Vector vector = new Vector();
				vector.add(rs.getInt(1));
				vector.add(rs.getString(2));
				vector.add(rs.getString(3));
				vector.add(rs.getFloat(4));
				vector.add(rs.getString(5));
				vector.add(rs.getString(6));
				dModel.addRow(vector);
				count++;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			BaseDao.close();
		}
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentChooseCourse(me).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable ChooseCourseShow;
	private javax.swing.JLabel Cno;
	private javax.swing.JTextField CnoText;
	private javax.swing.JLabel CnoType;
	private javax.swing.JTextField CnoTypeText;
	private javax.swing.JTable Course;
	private javax.swing.JButton Delete;
	private javax.swing.JButton FindB;
	private javax.swing.JButton OKB;
	private javax.swing.JButton ReSetQ;
	private javax.swing.JLabel Tno;
	private javax.swing.JTextField TnoType;
	private javax.swing.JLabel jLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable3;
	// End of variables declaration//GEN-END:variables

}